config/routes.rb
Rails.application.routes.draw do
  get 'buses/index'
  get 'buses/order_filter/:filter_option' => 'buses#order_filter', :as => 'buses_order_filter'

  get 'buses/show/:bus_id' => 'buses#show', :as => 'buses_show'
  get 'buses/edit/:bus_id' => 'buses#edit', :as => 'buses_edit'
  post 'buses/update/:bus_id' => 'buses#update', :as => 'buses_update'

  get 'buses/ratings/:bus_id' => 'buses#ratings', :as => 'buses_ratings'
  post 'buses/create_rating/:bus_id' => 'buses#create_rating', :as => 'buses_create_rating'
  get 'buses/get_bus_operators'

  root 'buses#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bus.rb
class Bus < ApplicationRecord
  has_many :ratings

  has_attached_file :icon, :styles => {:bigger => '300x122', :medium => '300x122', :thumb => '60x25'}
  has_attached_file :image, :styles => {:mdpi => '320x165', :hdpi => '480x248', :xhdpi => '640x331', :ios2x => '750x338', :ios3x => '1080x558'}

  validates_attachment_content_type :icon, content_type: /\Aimage\/.*\z/
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  def self.filter(filter_option)
    buses = self
    if filter_option.eql?('1')
      buses = self.group('buses.id').select('buses.id, buses.official_name, buses.icon_file_name, buses.icon_content_type, buses.icon_file_size, buses.icon_updated_at,
                        (buses.average_rating + (select COALESCE(sum(rating_total),0) from ratings where ratings.bus_id = buses.id)) / (CASE WHEN (select COALESCE(sum(rating_total),0) from ratings where ratings.bus_id = buses.id) = 0 THEN 1 ELSE 2 END) as rating_value')
                  .order('buses.official_name')
    elsif filter_option.eql?('2')
      buses = self.group('buses.id').select('buses.id, buses.official_name, buses.icon_file_name, buses.icon_content_type, buses.icon_file_size, buses.icon_updated_at,
                        (buses.average_rating + (select COALESCE(sum(rating_total),0) from ratings where ratings.bus_id = buses.id)) / (CASE WHEN (select COALESCE(sum(rating_total),0) from ratings where ratings.bus_id = buses.id) = 0 THEN 1 ELSE 2 END) as rating_value')
                  .order('rating_value DESC NULLS LAST')
    end
    buses
  end

  def self.only_ids
    self.ids
  end

  def self.deliver
    response = HTTParty.get('https://www.recorrido.cl/api/v2/es/bus_operators.json')
    response.parsed_response['bus_operators'].each do |bus_operator|
      unless Bus.only_ids.include? (bus_operator['id'])
        icon = URI.parse(bus_operator['icons']['bigger'])
        image = URI.parse(bus_operator['images']['ios3x'])
        Bus.create(
          :id => bus_operator['id'],
          :internal_name => bus_operator['internal_name'],
          :official_name => bus_operator['official_name'],
          :bookable => bus_operator['bookable'],
          :phone => bus_operator['phone'],
          :allows_e_ticketing => bus_operator['allows_e_ticketing'],
          :average_rating => bus_operator['average_rating'],
          :promotion_text => bus_operator['promotion_text'],
          :change_date_policy => bus_operator['change_date_policy'],
          :icon => icon,
          :image => image
        )
      end
    end
  end

  def calculate_rating
    average_rating = self.average_rating
    ratings = self.ratings.average(:rating_total)
    avg = (average_rating.zero? || average_rating.blank? || ratings.blank?) ? 1 : 2
    ((average_rating.blank? ? 0.0 : average_rating) + (ratings.blank? ? 0.0 : ratings)) / avg
  end
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :bus
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/buses_controller.rb
class BusesController < ApplicationController

  before_action :set_bus, :only => [:show, :edit, :update, :ratings, :create_rating]

  def index
    begin
      filter_option = session[:filter_option]
    rescue
      filter_option = nil
    end
    Bus.delay(queue: 'bus', priority: 20).deliver
    @buses = Bus.filter(filter_option).paginate(:page => params[:page], :per_page => 20)
  end

  def order_filter
    session.delete(:filter_option)
    session[:filter_option] = params[:filter_option]
    redirect_to buses_index_path
  end

  def show
    @rating = Rating.new
  end

  def edit
  end

  def update
    if @bus.update(bus_params)

    else

    end
    redirect_to buses_show_path(@bus)
  end

  def ratings

  end

  def create_rating
    rating = @bus.ratings.new(rating_params)
    if rating.save

    end
    redirect_to buses_show_path(@bus)
  end

  # Obtiene de manera directa los buses, se reemplazó por un background job en el modelo para que no tarde tanto.
  def get_bus_operators
    response = HTTParty.get('https://www.recorrido.cl/api/v2/es/bus_operators.json')
    response.parsed_response['bus_operators'].each do |bus_operator|
      unless Bus.only_ids.include? (bus_operator['id'])
        icon = URI.parse(bus_operator['icons']['bigger'])
        image = URI.parse(bus_operator['images']['ios3x'])
        Bus.create(
          :id => bus_operator['id'],
          :internal_name => bus_operator['internal_name'],
          :official_name => bus_operator['official_name'],
          :bookable => bus_operator['bookable'],
          :phone => bus_operator['phone'],
          :allows_e_ticketing => bus_operator['allows_e_ticketing'],
          :average_rating => bus_operator['average_rating'],
          :promotion_text => bus_operator['promotion_text'],
          :change_date_policy => bus_operator['change_date_policy'],
          :icon => icon,
          :image => image
        )
      end
    end
  end

  private

  def set_bus
    @bus = Bus.find(params[:bus_id])
  end

  def bus_params
    params.require(:bus).permit(:description)
  end

  def rating_params
    params.require(:rating).permit(:comment, :rating_total)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buses_helper.rb
module BusesHelper
end

app/views/buses/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <h4 class="page-title">Operador de Bus | <%= link_to "Ver #{@bus.official_name}", buses_show_path(@bus) %></h4>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <div class="card-box">
      <h4 class="header-title m-t-0 m-b-30"><%= @bus.official_name %></h4>

      <div class="row">
        <div class="col-lg-12">
          <%= form_tag buses_update_path(@bus), :class => 'form-horizontal' do %>
            <%= fields_for @bus do |f| %>
              <div class="form-group">
                <label class="col-md-2 control-label">Descripción</label>
                <div class="col-md-10">
                  <%= f.text_area :description, :class => 'form-control' %>
                </div>
              </div>
              <div class="p-t-10 pull-right">
                <%= f.submit 'Guardar', :class => 'btn btn-primary' %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/buses/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <h4 class="page-title">Lista de Operadores de Buses</h4>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <div class="card-box table-responsive">
      <div class="pull-right">
      <strong style="padding-right: 20px;">Ordenado Por:</strong>
      <%= select_tag :filter_option, options_for_select([['Nombre', '1'], ['Posición', '2']], :selected => session[:filter_option ]),
                                     { :class => 'btn btn-rounded btn-default pull-right w-lg m-b-5'} %>
      </div>
      <br><br><br>

      <table id="datatable" class="tablesaw m-t-20 table m-b-0 tablesaw-stack">
        <tbody>
          <% @buses.each do |bus| %>
            <tr>
              <td class="text-center"><%= image_tag bus.icon.url(:thumb) %></td>
              <td><h2><strong><%= bus.official_name %></strong></h2></td>
              <td class="text-center">
                <i class="fa fa-star fa-4x yellow" aria-hidden="true"></i><br>
                <span class="rating"> <%= bus.rating_value.blank? ? 0.0 : bus.rating_value %> de 5.0 </span>
              </td>
              <td class="pull-right">
                <%= link_to buses_show_path(bus), :class => 'btn btn-primary waves-effect waves-light m-b-5' do %>
                  <i class="fa fa-eye m-r-5"></i> <span>VER</span>
                <% end %>
                <%= link_to buses_edit_path(bus), :class => 'btn btn-info waves-effect waves-light m-b-5' do %>
                  <i class="fa fa-pencil m-r-5"></i> <span>EDITAR</span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= will_paginate @buses, renderer: BootstrapPagination::Rails, :previous_label => 'Anterior', :next_label => 'Siguiente' %>
    </div>
  </div>
</div>

<script>
  $( "#filter_option" ).change(function() {
    var url = "/buses/order_filter/"+$(this).val();
    window.location.replace(url);
  });
</script>

app/views/buses/ratings.html.erb
<!-- Vista basada en el mockup, se llevo directo a la vista del bus por un tema de diseño -->
<h1>Calificaciones de <%= @bus.official_name %> | <%= link_to 'Ver', buses_show_path(@bus) %></h1>

<ul>
  <% @bus.ratings.each do |rating| %>
    <li>
      Nota: <%= rating.rating_total %><br>
      Comentario: <%= rating.comment %>
    </li>
  <% end %>
</ul>

app/views/buses/show.html.erb
<div class="row">
  <div class="col-sm-12">
    <h4 class="page-title">Operador de Bus</h4>
  </div>
</div>

<div class="row">
  <div class="col-sm-8">
    <div class="bg-picture card-box">
      <div class="profile-info-name">
        <%= image_tag @bus.image.url(:mdpi), :class => 'image img-thumbnail', :alt => 'bus' %>

        <div class="profile-info-detail">
          <h3 class="m-t-0 m-b-0"><%= @bus.official_name %></h3>
          <p class="text-muted m-b-20"><i><%= image_tag @bus.icon.url(:thumb), :class => 'icon' %></i></p><br>
          <p><%= @bus.description.blank? ? 'Sin descripción' : @bus.description %></p>
          <div class="button-list m-t-20">
            <%= link_to buses_edit_path(@bus), :class => 'btn btn-facebook btn-sm waves-effect waves-light' do %>
              <i class="fa fa-pencil"></i> Editar
            <% end %>

            <%= link_to buses_ratings_path(@bus), :class => 'btn btn-facebook btn-sm waves-effect waves-light' do %>
              <i class="fa fa-eye"></i> Ver Calificaciones
            <% end %>
          </div>
        </div>
        <div class="clearfix"></div>
      </div>
    </div>

    <%= form_tag buses_create_rating_path(@bus), :class => 'card-box' do %>
      <h3>Calificar <strong class="pull-right text-warning"><%= @bus.calculate_rating.blank? ? 0.0 : @bus.calculate_rating %> de 5.0 </strong></h3>
      <%= fields_for @rating do |f| %>
        <span class="input-icon icon-right">
          <%= f.text_area :comment, :class => 'form-control', :placeholder => 'Escriba su comentario' %>
        </span>
        <div class="p-t-10 pull-right">
          <%= f.submit 'Enviar', :class => 'btn btn-primary' %>
        </div>
        <ul class="nav nav-pills profile-pills m-t-10">
          <li>
            <%= f.select :rating_total, options_for_select((1..5).to_a.map{|s| ["#{s}", s]}), {}, {:class => 'btn btn-purple btn-sm'} %>
          </li>
        </ul>
      <% end %>
    <% end %>
  </div>
  <div class="col-sm-4">
    <div class="card-box">
      <h4 class="header-title m-t-0 m-b-30"><i class="zmdi zmdi-notifications-none m-r-5"></i> Calificaciones</h4>
      <ul class="list-group m-b-0 user-list">
        <% @bus.ratings.each do |rating| %>
          <li class="list-group-item">
            <a class="user-list-item">
              <div class="avatar text-center">
                <i class="fa fa-star yellow"></i><br>
                <span><%= rating.rating_total %></span>
              </div>
              <div class="user-desc">
                <span class="name"><%= rating.comment %></span>
                <span class="desc"><%= rating.created_at %></span>
              </div>
            </a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recorrido Test</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header id="topnav">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="topbar-main">
          <div class="container">
            <div class="topbar-left">
              <%= link_to buses_index_path, :class => 'logo' do %>
                <span>Recorrido<span>Test</span></span>
              <% end %>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <div class="wrapper">
      <div class="container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>